FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy all files
COPY . .

EXPOSE 3000

# Run in development mode
CMD ["npm", "run", "dev"]
