services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    command: sh -c "npm install && npm run dev"
    networks:
      - valueverse-network

networks:
  valueverse-network:
    external: true
    name: services_valueverse-network
