# ============================================================================
# Prometheus Configuration for ValueVerse Platform
# ============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'valueverse-monitor'
    environment: 'development'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # Kong API Gateway metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
        labels:
          service: 'kong'
    metrics_path: '/metrics'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'

  # Microservices metrics
  - job_name: 'value-architect'
    static_configs:
      - targets: ['value-architect:8001']
        labels:
          service: 'value-architect'
          agent: 'architect'
    metrics_path: '/metrics'

  - job_name: 'value-committer'
    static_configs:
      - targets: ['value-committer:8002']
        labels:
          service: 'value-committer'
          agent: 'committer'
    metrics_path: '/metrics'

  - job_name: 'value-executor'
    static_configs:
      - targets: ['value-executor:8003']
        labels:
          service: 'value-executor'
          agent: 'executor'
    metrics_path: '/metrics'

  - job_name: 'value-amplifier'
    static_configs:
      - targets: ['value-amplifier:8004']
        labels:
          service: 'value-amplifier'
          agent: 'amplifier'
    metrics_path: '/metrics'

  - job_name: 'calculation-engine'
    static_configs:
      - targets: ['calculation-engine:8005']
        labels:
          service: 'calculation-engine'
          type: 'compute'
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8006']
        labels:
          service: 'notification-service'
          type: 'messaging'
    metrics_path: '/metrics'

  # Frontend metrics (if exposed)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
        labels:
          service: 'frontend'
          type: 'ui'
    metrics_path: '/api/metrics'

  # Docker containers metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
    metrics_path: '/metrics'

  # Consul service discovery (optional)
  - job_name: 'consul-services'
    consul_sd_configs:
      - server: 'consul:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: service
      - source_labels: [__meta_consul_node]
        target_label: node
      - source_labels: [__meta_consul_tags]
        target_label: tags

  # Kubernetes service discovery (optional for K8s deployment)
  # - job_name: 'kubernetes-pods'
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  #       action: keep
  #       regex: true
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
  #       action: replace
  #       target_label: __metrics_path__
  #       regex: (.+)
