version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/frontend/node_modules
      - venv:/workspace/backend/venv
    command: sleep infinity
    network_mode: service:db
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/valuedb
      - REDIS_URL=redis://localhost:6379
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  db:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=valuedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d valuedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
  node_modules:
  venv:
