# Prometheus Alert Rules for ValueVerse Platform

groups:
  # =====================================================
  # APPLICATION ALERTS
  # =====================================================
  
  - name: application_alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m])) 
            / 
            sum(rate(http_requests_total[5m]))
          ) > 0.01
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 1%)"
          runbook: "https://docs.valueverse.com/runbooks/high-error-rate"

      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint)
          ) > 0.5
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High API response time on {{ $labels.endpoint }}"
          description: "95th percentile response time is {{ $value }}s (threshold: 0.5s)"

      - alert: APIEndpointDown
        expr: up{job="backend"} == 0
        for: 2m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "Backend API instance {{ $labels.instance }} is down"
          description: "API endpoint has been down for more than 2 minutes"
          runbook: "https://docs.valueverse.com/runbooks/api-down"

  # =====================================================
  # DATABASE ALERTS
  # =====================================================
  
  - name: database_alerts
    interval: 30s
    rules:
      - alert: DatabaseConnectionPoolExhaustion
        expr: |
          (
            pg_stat_database_numbackends 
            / 
            pg_settings_max_connections
          ) > 0.8
        for: 5m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "PostgreSQL connection pool near exhaustion"
          description: "Database connections at {{ $value | humanizePercentage }} capacity"
          runbook: "https://docs.valueverse.com/runbooks/db-connections"

      - alert: DatabaseReplicationLag
        expr: pg_replication_lag_seconds > 300
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "PostgreSQL replication lag detected"
          description: "Replica is {{ $value }}s behind primary (threshold: 300s)"

      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "Database has been unreachable for more than 1 minute"
          runbook: "https://docs.valueverse.com/runbooks/db-down"

      - alert: SlowQueries
        expr: |
          rate(pg_stat_statements_mean_exec_time_seconds[5m]) > 1
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Slow database queries detected"
          description: "Average query execution time is {{ $value }}s"

      - alert: HighDiskUsage
        expr: |
          (
            pg_database_size_bytes 
            / 
            node_filesystem_size_bytes{mountpoint="/var/lib/postgresql/data"}
          ) > 0.8
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "Database disk usage high"
          description: "Disk usage at {{ $value | humanizePercentage }}"

  # =====================================================
  # CACHE & REDIS ALERTS
  # =====================================================
  
  - name: redis_alerts
    interval: 30s
    rules:
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "Redis cache is down"
          description: "Redis has been unreachable for more than 2 minutes"

      - alert: RedisHighMemoryUsage
        expr: |
          (
            redis_memory_used_bytes 
            / 
            redis_memory_max_bytes
          ) > 0.9
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Redis memory usage high"
          description: "Memory usage at {{ $value | humanizePercentage }}"

      - alert: RedisLowCacheHitRate
        expr: |
          (
            rate(redis_keyspace_hits_total[5m]) 
            / 
            (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m]))
          ) < 0.8
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Redis cache hit rate low"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 80%)"

  # =====================================================
  # SYSTEM & INFRASTRUCTURE ALERTS
  # =====================================================
  
  - name: system_alerts
    interval: 30s
    rules:
      - alert: HighCPUUsage
        expr: |
          (
            100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
          ) > 80
        for: 10m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% (threshold: 80%)"

      - alert: HighMemoryUsage
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) 
            / 
            node_memory_MemTotal_bytes
          ) > 0.85
        for: 10m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: DiskSpaceLow
        expr: |
          (
            node_filesystem_avail_bytes{mountpoint="/"} 
            / 
            node_filesystem_size_bytes{mountpoint="/"}
          ) < 0.2
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Only {{ $value | humanizePercentage }} disk space remaining"

      - alert: ContainerDown
        expr: absent(container_last_seen{name=~".+"})
        for: 2m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "Container has been down for more than 2 minutes"

  # =====================================================
  # WEBSOCKET ALERTS
  # =====================================================
  
  - name: websocket_alerts
    interval: 30s
    rules:
      - alert: HighWebSocketConnections
        expr: websocket_connections_active > 9000
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High number of WebSocket connections"
          description: "Active WebSocket connections: {{ $value }} (max: 10000)"

      - alert: WebSocketConnectionFailures
        expr: rate(websocket_connection_failures_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High WebSocket connection failure rate"
          description: "Connection failures: {{ $value }}/s"

  # =====================================================
  # SECURITY ALERTS
  # =====================================================
  
  - name: security_alerts
    interval: 30s
    rules:
      - alert: HighAuthenticationFailures
        expr: rate(auth_failures_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failures: {{ $value }}/s from {{ $labels.ip }}"

      - alert: RateLimitExceeded
        expr: rate(rate_limit_exceeded_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Rate limit frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times/s"

      - alert: SuspiciousActivity
        expr: rate(http_requests_total{status="403"}[5m]) > 50
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High rate of forbidden requests"
          description: "403 responses: {{ $value }}/s - possible attack"

  # =====================================================
  # BACKUP & DATA ALERTS
  # =====================================================
  
  - name: backup_alerts
    interval: 1h
    rules:
      - alert: BackupFailed
        expr: time() - backup_last_success_timestamp_seconds > 7200
        for: 10m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "Database backup has failed"
          description: "Last successful backup was {{ $value | humanizeDuration }} ago"
          runbook: "https://docs.valueverse.com/runbooks/backup-failure"

      - alert: BackupSizeTooLarge
        expr: backup_size_bytes > 100000000000  # 100GB
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "Backup size unusually large"
          description: "Backup size is {{ $value | humanize1024 }}B"

  # =====================================================
  # SSL/TLS CERTIFICATE ALERTS
  # =====================================================
  
  - name: certificate_alerts
    interval: 1h
    rules:
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "SSL certificate expiring soon"
          description: "Certificate for {{ $labels.domain }} expires in {{ $value }} days"

      - alert: SSLCertificateExpired
        expr: ssl_certificate_expiry_seconds - time() < 0
        for: 5m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "SSL certificate has expired"
          description: "Certificate for {{ $labels.domain }} is expired"
          runbook: "https://docs.valueverse.com/runbooks/ssl-expired"
