name: AI-Powered Development

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to develop"
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  develop-feature:
    if: contains(github.event.issue.labels.*.name, 'auto-develop') || contains(github.event.comment.body, '/develop')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install httpx pygithub anthropic openai

      - name: Run Agentic Development System
        env:
          AI_PROVIDER: ${{ secrets.AI_PROVIDER || 'together' }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/agentic_developer.py

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
        run: |
          issue_num=$ISSUE_NUMBER
          branch="ai-feature-${issue_num}"

          # Configure git
          git config user.name "AI Developer Bot"
          git config user.email "ai-dev@valueverse.dev"

          # Create and push branch
          git checkout -b "$branch"
          git add .

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "feat: AI-generated implementation for issue #${issue_num}

          This implementation was automatically generated by the AI Development Workflow.

          Components generated:
          - Backend API endpoints and services
          - Frontend React components
          - Comprehensive test suite
          - Documentation updates

          Generated using Claude-3-Opus and GPT-4

          Closes #${issue_num}"

          git push origin "$branch"

          # Read development summary
          if [ -f "ai_development_summary.json" ]; then
            summary=$(cat ai_development_summary.json)
            files_created=$(echo "$summary" | jq -r '.files_created[]' | sed 's/^/- /')
            total_files=$(echo "$summary" | jq -r '.total_files')
            total_lines=$(echo "$summary" | jq -r '.total_lines')
          else
            files_created="- (see commits)"
            total_files="N/A"
            total_lines="N/A"
          fi

          # Create PR
          gh pr create \
            --title "🤖 Agentic AI: Issue #${issue_num}" \
            --body "## 🤖 Autonomous AI Development

          **Related Issue**: Closes #${issue_num}

          This PR was created by our **Agentic Development System** - a multi-agent AI that autonomously:
          1. 🏗️ Designed the architecture
          2. 📋 Created an implementation plan
          3. 💻 Generated all code
          4. 🧪 Wrote comprehensive tests
          5. 🔍 Reviewed for quality & security

          ### 📊 Development Summary

          - **Files Created**: ${total_files}
          - **Total Lines**: ${total_lines}
          - **Provider**: ${AI_PROVIDER:-together}

          ### 📁 Files Generated

          ${files_created}

          ### 🔍 Review Checklist

          - [ ] Code follows ValueVerse standards
          - [ ] Tests pass and coverage meets requirements
          - [ ] Security requirements validated
          - [ ] No hardcoded secrets or credentials
          - [ ] Documentation is complete

          ### 🤖 Agentic AI System

          This code was generated by specialized AI agents:
          - **Architect Agent**: System design
          - **Planner Agent**: Task breakdown
          - **Implementation Agent**: Code generation
          - **Tester Agent**: Test creation
          - **Reviewer Agent**: Quality assurance

          ---

          **⚠️ Important**: This is AI-generated code. Human review is **required** before merging." \
            --label "auto-generated" \
            --label "needs-review"

          # Comment on issue
          pr_url=$(gh pr list --head "$branch" --json url --jq '.[0].url')
          gh issue comment $issue_num --body "🤖 **AI Development Complete!**

          I've created a pull request with the implementation: $pr_url

          The PR includes:
          - ✅ Backend implementation (FastAPI)
          - ✅ Frontend components (Next.js + React)
          - ✅ Test suite with coverage
          - ✅ Documentation

          Please review the code and provide feedback!"
