name: AI Development (Multi-Provider)

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number'
        required: true
        type: number
      ai_provider:
        description: 'AI Provider to use'
        required: false
        default: 'openrouter'
        type: choice
        options:
          - openrouter
          - together
          - windsurf
          - anthropic
          - openai

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  develop-feature:
    if: contains(github.event.issue.labels.*.name, 'auto-develop') || contains(github.event.comment.body, '/develop')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install httpx pygithub anthropic openai
      
      - name: Generate implementation
        env:
          # Configure AI Provider (default: openrouter)
          AI_PROVIDER: ${{ inputs.ai_provider || 'openrouter' }}
          
          # API Keys for different providers
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          WINDSURF_API_KEY: ${{ secrets.WINDSURF_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
          # Model preferences (optional, uses defaults if not set)
          OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL || 'anthropic/claude-3-opus' }}
          TOGETHER_MODEL: ${{ secrets.TOGETHER_MODEL || 'meta-llama/Llama-3-70b-chat-hf' }}
          
          # GitHub info
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/ai_developer_multi_provider.py
      
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
          AI_PROVIDER: ${{ inputs.ai_provider || 'openrouter' }}
        run: |
          issue_num=$ISSUE_NUMBER
          branch="ai-feature-${issue_num}"
          
          git config user.name "AI Developer Bot"
          git config user.email "ai-dev@valueverse.dev"
          git checkout -b "$branch"
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes generated"
            exit 0
          fi
          
          git commit -m "feat: AI implementation for issue #${issue_num}

          Auto-generated using ${AI_PROVIDER} AI provider.
          
          Closes #${issue_num}"
          
          git push origin "$branch"
          
          gh pr create \
            --title "🤖 AI: Issue #${issue_num}" \
            --body "## AI-Generated Implementation

          **Related**: Closes #${issue_num}
          **AI Provider**: ${AI_PROVIDER}
          
          ### Generated Components
          - ✅ Backend services (FastAPI)
          - ✅ Frontend components (React/TypeScript)
          - ✅ Comprehensive tests
          - ✅ Documentation
          
          ### Review Checklist
          - [ ] Security requirements met
          - [ ] Tests pass (80%+ coverage)
          - [ ] Code follows ValueVerse standards
          - [ ] Documentation complete
          
          ---
          Generated by ${AI_PROVIDER} AI. Human review required." \
            --label "auto-generated" \
            --label "needs-review"
          
          gh issue comment $issue_num --body "🤖 Implementation complete using **${AI_PROVIDER}** AI!

          PR created: $(gh pr list --head $branch --json url --jq '.[0].url')
          
          Ready for review!"
