name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main ]

jobs:
  backend-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - billing-system/backend
          - services/value-architect
          - services/value-committer
          - services/value-executor
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pytest-asyncio black ruff mypy
    
    - name: Lint with ruff
      run: |
        cd ${{ matrix.service }}
        ruff check . || true
    
    - name: Type check with mypy
      run: |
        cd ${{ matrix.service }}
        mypy . --ignore-missing-imports || true
    
    - name: Run tests with coverage
      run: |
        cd ${{ matrix.service }}
        pytest tests/ --cov=. --cov-report=xml --cov-report=term --cov-fail-under=80 || true
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./${{ matrix.service }}/coverage.xml
        flags: ${{ matrix.service }}

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Lint and format
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
